export const ROUTES = {
  // Public
  HOME: "/",
  PROJECTS: "/apartments",
  PROJECT_DETAIL: (slug: string) => `/apartments/${slug}`,
  PROPERTIES: "/properties",
  PROPERTY_DETAIL: (slug: string) => `/properties/${slug}`,
  MAP_SEARCH: "/map-search",
  COMPARE: "/compare",
  CONSULTATION: "/consultation",
  ABOUT: "/about-us",
  CONTACT: "/contact-us",
  BLOG: "/blog",
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  AGENTS: "/agents",
  AGENT_DETAIL: (slug: string) => `/agents/${slug}`,
  MARKETPLACE: "/marketplace",
  MARKETPLACE_CATEGORY: (slug: string) => `/marketplace/category/${slug}`,
  MARKETPLACE_SUPPLIER: (slug: string) => `/marketplace/supplier/${slug}`,
  MARKETPLACE_PRODUCT: (slug: string) => `/marketplace/product/${slug}`,
  MARKETPLACE_CART: "/marketplace/cart",
  MARKETPLACE_REQUEST: "/marketplace/request",
  MARKETPLACE_QUOTE: "/marketplace/quote",
  MARKETPLACE_QUOTE_THANK_YOU: "/marketplace/quote/thank-you",
  PRE_APPROVAL: "/pre-approval",
  MOVING_CHECKLIST: "/moving-checklist",
  PARTNER: (type: "supplier" | "investor") => `/partner/${type}`,
  BECOME_SUPPLIER: "/partner/supplier",
  BECOME_INVESTOR: "/partner/investor",
  OFFER_NEW: (propertySlug: string) => `/properties/${propertySlug}/offer`,
  NOTIFICATIONS: "/notifications",
  PRIVACY: "/privacy",
  TERMS: "/terms",

  // Auth
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  UNAUTHORIZED: "/unauthorized",

  // Admin dashboard
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_PROJECT_CREATE: "/admin/projects/create",
  ADMIN_PROJECT_EDIT: (id: string) => `/admin/projects/${id}/edit`,
  ADMIN_PROPERTIES: "/admin/properties",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_DETAIL: (id: string) => `/admin/users/${id}`,
  ADMIN_SELLERS: "/admin/sellers",
  ADMIN_INQUIRIES: "/admin/inquiries",
  ADMIN_INQUIRY_DETAIL: (id: string) => `/admin/inquiries/${id}`,
  ADMIN_SUPPLIER_REQUESTS: "/admin/supplier-requests",
  ADMIN_INVESTOR_REQUESTS: "/admin/investor-requests",
  ADMIN_MARKETPLACE_TAXONOMY: "/admin/marketplace/taxonomy",
  ADMIN_MARKETPLACE_CATEGORIES: "/admin/marketplace/categories",
  ADMIN_MARKETPLACE_SUPPLIERS: "/admin/marketplace/suppliers",
  ADMIN_MARKETPLACE_QUOTES: "/admin/marketplace-quotes",
  ADMIN_MARKETPLACE_QUOTE_DETAIL: (id: string) => `/admin/marketplace-quotes/${id}`,
  ADMIN_BOOKINGS: "/admin/bookings",
  ADMIN_BOOKING_DETAIL: (id: string) => `/admin/bookings/${id}`,
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_BLOG: "/admin/blog",
  ADMIN_BLOG_CREATE: "/admin/blog/create",
  ADMIN_BLOG_EDIT: (id: string) => `/admin/blog/${id}/edit`,
  ADMIN_HERO_SLIDES: "/admin/hero-slides",
  ADMIN_HERO_SLIDE_CREATE: "/admin/hero-slides/create",
  ADMIN_HERO_SLIDE_EDIT: (id: string) => `/admin/hero-slides/${id}/edit`,
  ADMIN_SETTINGS: "/admin/settings",

  // Seller dashboard
  SELLER_DASHBOARD: "/seller/dashboard",
  SELLER_PROPERTIES: "/seller/properties",
  SELLER_PROPERTY_CREATE: "/seller/properties/create",
  SELLER_PROPERTY_EDIT: (id: string) => `/seller/properties/${id}/edit`,
  SELLER_INQUIRIES: "/seller/inquiries",
  SELLER_INQUIRY_DETAIL: (id: string) => `/seller/inquiries/${id}`,
  SELLER_MARKETPLACE_CATALOGUE: "/seller/marketplace-catalogue",
  SELLER_BOOKINGS: "/seller/bookings",
  SELLER_PROFILE: "/seller/profile",

  // Buyer dashboard
  BUYER_DASHBOARD: "/buyer/dashboard",
  BUYER_SAVED: "/buyer/saved-properties",
  BUYER_SEARCHES: "/buyer/recent-searches",
  BUYER_INQUIRIES: "/buyer/inquiries",
  BUYER_INQUIRY_DETAIL: (id: string) => `/buyer/inquiries/${id}`,
  BUYER_MARKETPLACE_QUOTES: "/buyer/marketplace-quotes",
  BUYER_MARKETPLACE_QUOTE_DETAIL: (id: string) => `/buyer/marketplace-quotes/${id}`,
  BUYER_BOOKINGS: "/buyer/bookings",
  BUYER_PROFILE: "/buyer/profile",

  // Backend API endpoints (served by NestJS at NEXT_PUBLIC_API_BASE_URL,
  // defaults to http://localhost:3001/api/v1). Use these only for direct
  // references — the typed `httpClient` in src/services/ already prepends
  // the base URL.
  API: {
    PROJECTS: "/projects",
    PROJECT: (slug: string) => `/projects/${slug}`,
    PROPERTIES: "/properties",
    PROPERTY: (slug: string) => `/properties/${slug}`,
    INQUIRIES: "/inquiries",
    BOOKINGS: "/bookings",
    USERS: "/users",
    DASHBOARD_STATS: "/dashboard/stats",
    AUTH: "/auth",
    AGENTS: "/agents",
    AGENT: (slug: string) => `/agents/${slug}`,
    REVIEWS: "/reviews",
    QA: "/qa",
    NOTIFICATIONS: "/notifications",
    DOCUMENTS: "/documents",
    BANKS: "/banks",
    OFFERS: "/offers",
    PRE_APPROVAL: "/pre-approval",
    MARKETPLACE_CATEGORIES: "/marketplace/categories",
    MARKETPLACE_PRODUCTS: "/marketplace/products",
    MARKETPLACE_SUPPLIERS: "/marketplace/suppliers",
    MARKETPLACE_QUOTES: "/marketplace/quotes",
    MARKETPLACE_ADMIN_CATEGORIES: "/marketplace/admin/categories",
    MARKETPLACE_ADMIN_CATEGORY: (slug: string) => `/marketplace/admin/categories/${slug}`,
    HERO_SLIDES: "/hero-slides",
    HERO_SLIDE: (id: string) => `/hero-slides/${id}`,
  },
} as const
